name: LaTeX Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex

    - name: Check for LaTeX errors and warnings
      run: |
        if grep -q "^!" main.log; then
          echo "LaTeX errors found:"
          grep "^!" main.log
          exit 1
        elif grep -q "Warning:" main.log; then
          echo "LaTeX warnings found:"
          grep "Warning:" main.log
          echo "Build completed with warnings."
        else
          echo "LaTeX build completed successfully without errors or warnings."
        fi

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }} ${{ github.event.head_commit.message }}
        tag_name: ${{ github.ref_name }}
        files: main.pdf
